sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run ./postmantests/postman_collection.json -e ./postmantests/postman_environment.json
after_success:
- docker login -p $DOCKER_PASS -u $DOCKER_USER
- docker build -t paulspencer/lab2 .
- docker tag paulspencer/lab2 paulspencer/lab2
- docker push paulspencer/lab2
env:
  global:
  - secure: ktaqEaNZDU1nrwboV2UKOOtFaar3vzhE+iA58L5k9m8GSAy4HWwaqVjKoG3NnhnBgmqPtd5sHNVT6Va/ocZO2CNPYwSl6YOZ/vJWDiIb6lCYFVT6yOq9p3fOUMNnoc0+ubTpoRGEIDzWlJKu4sufeCC/Qq9P9rfUpBvGXPFBdZjjpCBZ6ltZhbEYBNCBFVrRSlGan2SIKbi5Vhg6X4bVGfDqPIlPB42Eyv/vQsjuRRkC6Zwj7EbxkT+9Z4XIWesk6CbkyzZVEqPZ9wpejnTFRuu8l3EibtzqMoENd1JkUNMK+QPR6KqtmKD9zf+VW4gPExBcKiYUGyM/AuK8AMlXiqKVKfdT/qb6OQekDe8KKu0Kxh8vsPqHnbpaFQ5d7ndM1XyGvTU3Uu6r4x+qppRKjYPZCFgbYjR9FBGoU1A2eQZy+v/4DHnxgvWfaUK0n3Fk1PG+H3yekb10Kv5t2FaQdsPgbq8DmJLiZr2qjkd4e8d2183F1QtezJKkeJ9OHDlCYSNl6uFBB/WbxdkzUT6H6etoN746wSgnbk2F3CVjZ/2tPZxvtgqV0Oa6zz+bVswfGO8ri6xF0v3nB5z/9ie43DvuSTWJ7qHuRdAgobQWDVfFpnLGQZDaYxoeGwh2h9455QbK+EAmUiu7ZDTvGCrydAI3fBcpEBRkDDamV1OhMok=
  - secure: BKbu4hW01AQrngkYkBSv+Q0g0hObIiuw8ueeMrLy6seoxv2V1dBlh2zob02kh7XZnxNteCQ2ayJYNOAnrUwVynjbTp1ByFVWdPOD4XQhri2MW4zZmNRj9sFfHskss/RiuL9fr5YAJHclo0UpI3uqUmM3M0dUDvM3TV6cBKkasHMn/3NQQbjRrvt1tWXheTq/ajdiAmFqkBrY5NxsFb81l/kwhmNd2P8IC3l2fev0WBLm+jRMXeD+aZLLP2mpqwSKCn/MMNQ+pMKxmQlwkxv9r3OghQ7KPGjL2WYvG6GOhh/PLqHkr3zHnJglLDSciR9bRyRtlSkNdHhK2taj4U/5/0VksUUEsu2rWOBXLCoapXGJ8YBWtBubvmmgXh0M9txC2n9Y3rqfHY4HGPp4Xnrq8ES7/gacNVNxtX8ErFMVV1x0eFiK9CDF3S5I1PHrdEnXUcBhOoxV79taEU0P2rn0r5m9PToJWLbw7lFO84SODwzB6tSAefZJO9BjLyqfD9Vnax6aeENsz37+TuBRCeI+5i4BAvJEHaUl1DZu0B8YcrCFKDgB/tsuzWniwLdmatCO71QaaF4tulCLBcrE5T7qq/itR2JltgfLhz0HhTY68c1AfvWC3ozJv9T9exEsrsRQ8UV/WHFxF7qUS68FIkP4wjHc5rwFK9PgVIsFTntK4Z4=
