sudo: required
services:
- docker
language: python
python:
- '3.6'
before_install:
- docker version
- docker info
install:
- npm install newman
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install nose
- pip install Flask-Testing
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- python -m unittest discover
- docker build -t swagger-spring-example:1.0.0 .
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run ./postmantests/postman_collection.json -e ./postmantests/postman_environment.json
env:
  global:
  - secure: mwr8Ql7scjN5gVawlvEWKaxZQy0IxRdN6kZ7NHxFXATi78PTeXNUuMS6vn5BLiMRc5ZWW8h1yStrwuRuplqqeSRK0GyWKGDMiXgonz6AME1NxFTo7zRXKJON9/g1bxuzXobhBB+2LmvpGVbdsRbT0xDSn8lwFLVOQIIko7TYVMhcG2STwYVdf5gL+AP4FBjwVb6pAWbadwuG6r5Q/3ngLQyyKaf+oL6RbG4yLGSDg/aeJRXSvqIxJ8MN2Wv9mhY4fCV8oJrwUigfIMvHGCgcp1Yl7qpvE8laeYzPZhHtAwmTGmPsMmCxTkpkdg5G7hsDYbgjMy2pNjY7MR27WaxaBiL/vnvKZt5pgI0fq34xoRfh3YtDi5TxDxnJfXl5kQAGpwcyIhqjRwU6svtNAglhy6mN2c3lqvAHCN/qmxhc15kvoGq1qEJFmJ2+qWjpX8hnE7zs2i595R/N4Ywv6mHppyyQOQ0Hy/sxW087G3iZZjOfsE0b0cvDIg/3Lvv7jZTForkeGz3N92+irQ2YxtmkoB59nsd4h8pAMXVPHycKfmAnTlwoQ0VIKEEsKg9vSs/x0nax3mV0g07Hg85kpRTMrMjKNe8UVNAu0taiCCzF2hMZHaJDPGp2eFfUGXSx/E6Gc2ht55k9ZXeDVg4tjqvkOkxJ562Ia0vs2kIAwmeo180=
  - secure: OKdID2pLGnzs2uD/FmLiKEMKcdyudPIvnKA2O0+T4Vc2zsz9lhwM7hKGUOfD5Oz4JOAZzjoRPi/jqiU/Z0XnbwZP/IWpUdWFiAWYAKEYrMHWQ9QM9BFD72BFD4t3KCnCZgttwednjfDHJ6BMzi8nyKOGhkjvL5D7GcmmMaH3tBdfJPCJkStSYE9C7ZfulaoAxFBs3BlKsyFUg9Ps33CsrX9npwfi/tTm1Q/sSXf3SLVvdY3sZe+117pVAjUk+TgBZ5WijgndkGGyZhXA3K1vx2jclcY6xZtTlZN5/VWP3p/NIzaJXDnHZVcavaoBfEGhSxhqCRybuX4xW7fnVr64vi73jACWW4n3660MAZlsm3oFp5Rr/lBPlheQvC24RI92dSs9ZO9Q32pz4QCJNAbOu0462OjkEz90XaODzcikKLuJgBLbEqVBY4fTGmbPVJ+tu13AtFKJ+Vvll/bGdwKvCXUEVpXXc+DRAZhKKNK0EsOC3XCUP7fno3g8YxBrYJRby8QRixDfd98hp9OGanfEb4NFAeslQ4Cc9EQmWYnznPZg1b75OAEGjjDbB2153z2eQPvHrZDg7PJYOjS7hRmjorEO1dGPH3wLPeCkw+bRYfJkYHqaJeeUF4qW6wiSij0zDGmkcHBijmhLowb2wRPc8NZUu6zaJn3+f45r56yMZB8=
after_success:
- docker login -p $DOCKER_PASS -u $ DOCKER_USER 
- docker build -t paulspencer/lab2 .
- docker tag paulspencer/lab2 paulspencer/lab2
- docker push paulspencer/lab2
